#!/bin/sh
set -eo pipefail;

export DUCKU_ROOT=${DUCKU_ROOT:="$HOME"}
export DUCKU=${DUCKU:="/usr/local/bin/ducku"}

[[ $DUCKU_TRACE ]] && set -x

git_archive_all() {
  APP=$1; REV=$2
  TMP_WORK_DIR=$(mktemp -d)
  chmod 755 $TMP_WORK_DIR
  unset GIT_DIR GIT_WORK_TREE
  git clone $DUCKU_ROOT/$APP $TMP_WORK_DIR > /dev/null 2>&1

  cd $TMP_WORK_DIR
  git config advice.detachedHead false
  git checkout $REV > /dev/null 2>&1
  find -name .git -prune -exec rm -rf {} \; > /dev/null
  tar c .
  cd $DUCKU_ROOT
  rm -rf $TMP_WORK_DIR > /dev/null
}

case "$1" in
  receive)
    APP="$2"
    echo "---> Building $APP ..."
    cat | $DUCKU build $APP
    echo "---> Deploying $APP ..."
    $DUCKU deploy $APP
    echo "---> Application deployed"
    sudo backup <<END
y
END
    echo
    ;;

  receive-gzip)
    APP="$2"
    cat > $DUCKU_ROOT/app.tar.gz
    mkdir -p $DUCKU_ROOT/run
    tar -xf $DUCKU_ROOT/app.tar.gz -C $DUCKU_ROOT/run
    rm $DUCKU_ROOT/app.tar.gz
    $DUCKU deploy
    ;;

  build)
    APP="$2"
    DUCKU_RUN=$DUCKU_ROOT/run
    rm -rf $DUCKU_RUN && mkdir $DUCKU_RUN
    cat | tar -xC $DUCKU_ROOT/run
    ;;

  deploy)
    [[ `pidof node` ]] && sudo killall node
    # Node binds both input/output which hangs the deploy unless we redirect output/input
    sudo nohup node $DUCKU_ROOT/run/app.js >$DUCKU_ROOT/run.log 2>&1 </dev/null &
    ;;

  shell)
    /bin/bash
    ;;

  git-hook)
    APP="$2"

    while read oldrev newrev refname
    do
      # Only run this script for the master branch. You can remove this
      # if block if you wish to run it for others as well.
      if [[ $refname = "refs/heads/master" ]] ; then
        git_archive_all $APP $newrev | $DUCKU receive $APP
      else
        echo "-----> WARNING: deploy did not complete, you must push to master."
        echo "-----> for example, try 'git push <duck> ${refname/refs\/heads\/}:master'"
      fi

    done
    ;;

  git-*)

    APP="$(echo $2 | cut -d"'" -f 2)"

    # Would be nicer to put the checkout in ~/repos or something
    # but have banged my head against getting git-receive-pack to
    # honour any changes to the push path for way too long
    APP_PATH=$DUCKU_ROOT/$APP

    if [[ $1 == "git-receive-pack" && ! -d "$APP_PATH/refs" ]]; then
      git init --bare $APP_PATH > /dev/null
      PRERECEIVE_HOOK="$APP_PATH/hooks/pre-receive"
      cat > $PRERECEIVE_HOOK <<EOF
#!/bin/sh
set -e; set -o pipefail;
cat | $DUCKU git-hook $APP
EOF
      chmod +x $PRERECEIVE_HOOK
    fi

    args=$@
    git-shell -c "$args"
    ;;

  help)
    cat
    ;;
esac
