#!/bin/sh
set -eo pipefail;

export DUCKU_ROOT=${DUCKU_ROOT:="/home/duck"}
export DUCKU=${DUCKU:="/usr/local/bin/ducku"}

[[ $DUCKU_TRACE ]] && set -x

git_archive_all() {
  APP=$1; REV=$2
  TMP_WORK_DIR=$(mktemp -d)
  chmod 755 $TMP_WORK_DIR
  unset GIT_DIR GIT_WORK_TREE
  git clone $DUCKU_ROOT/$APP $TMP_WORK_DIR > /dev/null 2>&1

  cd $TMP_WORK_DIR
  git config advice.detachedHead false
  git checkout $REV > /dev/null 2>&1
  find -name .git -prune -exec rm -rf {} \; > /dev/null
  tar c .
  cd $DUCKU_ROOT
  rm -rf $TMP_WORK_DIR > /dev/null
}

detect_lang() {
  if [ -f $1/app.js ]; then
    echo "nodejs"
  elif [ -f $1/app.py ]; then
    echo "python"
  elif [ -f $1/app.rb ]; then
    echo "ruby"
  else
    echo ""
  fi
}

assert_lang() {
  case "$1" in
    nodejs)
      echo "--->" $(tce-load -wi nodejs)
      # Check if package.json exists and run npm install
      if [ -f $DUCKU_ROOT/run/package.json ]; then
        echo "--->" $(npm install --prefix $DUCKU_ROOT/run)
      fi
    ;;
    python)
      echo "--->" $(tce-load -wi python)
    ;;
    ruby)
      echo "--->" $(tce-load -wi ruby-2.1)
    ;;
  esac
}

case "$1" in
  receive)
    APP="$2"
    echo "---> Building $APP..."
    cat | $DUCKU build $APP
    $DUCKU execute
    echo
    ;;

  receive-gzip)
    APP="$2"
    echo "---> Receiving $APP..."
    cat > $DUCKU_ROOT/app.tar.gz
    echo "---> Building $APP..."
    DUCKU_RUN=$DUCKU_ROOT/run
    rm -rf $DUCKU_RUN && mkdir $DUCKU_RUN
    tar -xf $DUCKU_ROOT/app.tar.gz -C $DUCKU_RUN
    rm $DUCKU_ROOT/app.tar.gz
    $DUCKU execute
    ;;

  build)
    APP="$2"
    DUCKU_RUN=$DUCKU_ROOT/run
    rm -rf $DUCKU_RUN && mkdir $DUCKU_RUN
    cat | tar -xC $DUCKU_RUN
    ;;

  execute)
    lang=$(detect_lang $DUCKU_ROOT/run)
    if [ $lang ]; then
      echo "---> $lang app detected..."
      assert_lang $lang
      echo "---> "$(sudo filetool.sh -b)
      $DUCKU execute-$lang
      echo "---> Application deployed"
    else
      echo "---> Oops! No supported app detected..."
      echo "---> Please ensure an appropriate file is present:"
      echo "---> - Node.js needs an 'app.js'"
      echo "---> - Python needs an 'app.py'"
      echo "---> - Ruby needs an 'app.rb'"
      echo "---> Or, add 'execute.sh' to run something custom."
    fi
    ;;

  execute-nodejs)
    [[ `pidof node` ]] && sudo killall node
    # Node binds both input/output which hangs the deploy unless we redirect output/input
    sudo nohup node $DUCKU_ROOT/run/app.js >$DUCKU_ROOT/run.log 2>&1 </dev/null &
    ;;

  execute-python)
    [[ `pidof python` ]] && sudo killall python
    sudo nohup python $DUCKU_ROOT/run/app.py >$DUCKU_ROOT/run.log 2>&1 </dev/null &
    ;;

  execute-ruby)
    [[ `pidof ruby` ]] && sudo killall ruby
    sudo nohup ruby $DUCKU_ROOT/run/app.rb >$DUCKU_ROOT/run.log 2>&1 </dev/null &
    ;;

  execute-custom)
    [[ `pidof execute.sh` ]] && sudo killall execute
    sudo nohup $DUCKU_ROOT/run/execute.sh >$DUCKU_ROOT/run.log 2>&1 </dev/null &
    ;;

  shell)
    /bin/bash
    ;;

  config-wifi)
    # Ensure wifi package is installed
    echo "--->" $(tce-load -wi wifi)
    sudo wifi.sh
    ;;

  git-hook)
    APP="$2"

    while read oldrev newrev refname
    do
      # Only run this script for the master branch. You can remove this
      # if block if you wish to run it for others as well.
      if [[ $refname = "refs/heads/master" ]] ; then
        git_archive_all $APP $newrev | $DUCKU receive $APP
      else
        echo "-----> WARNING: deploy did not complete, you must push to master."
        echo "-----> for example, try 'git push <duck> ${refname/refs\/heads\/}:master'"
      fi

    done
    ;;

  git-*)

    APP="$(echo $2 | cut -d"'" -f 2)"

    # Would be nicer to put the checkout in ~/repos or something
    # but have banged my head against getting git-receive-pack to
    # honour any changes to the push path for way too long
    APP_PATH=$DUCKU_ROOT/$APP

    if [[ $1 == "git-receive-pack" && ! -d "$APP_PATH/refs" ]]; then
      git init --bare $APP_PATH > /dev/null
      PRERECEIVE_HOOK="$APP_PATH/hooks/pre-receive"
      cat > $PRERECEIVE_HOOK <<EOF
#!/bin/sh
set -e; set -o pipefail;
cat | $DUCKU git-hook $APP
EOF
      chmod +x $PRERECEIVE_HOOK
    fi

    args=$@
    git-shell -c "$args"
    ;;

  help)
    cat
    ;;
esac
