#!/bin/sh

# set -x

# if [[ $(id -un) != "root" ]]; then
#   sudo -u root -H $0 "$@"
#   exit
# fi

# We need at least one argument
if [ $# -lt 1 ]
  then $0 "help"
  exit 1
fi

duck_tmp="$HOME/.duck"
[[ -d $duck_tmp ]] || mkdir $duck_tmp
duckos_latest="http://localhost/duckos/duckos-rpi.img.gz"
duckos_img=$duck_tmp/duckos-rpi.img.gz

case "$1" in
  write)
    # Ensure we have a copy of duckos
    if [[ -f $duckos_img ]]
      then echo "---> Using $duckos_img"
      else echo "---> Downloading latest DuckOS..."
        curl $duckos_latest -o $duckos_img
    fi

    read -r -p "Select disk device (data will be destroyed): " disk_device

    # ensure our device is unmounted
    for filesystem in `ls -1 $disk_device?*`; do
        sudo umount -f $filesystem
    done

    sudo umount -f $disk_device

    echo "---> Writing DuckOS to $disk_device..."

    # write disk image to device
    ./bar -c 'gunzip -c' $duckos_img | sudo dd of=$disk_device

    echo "---> DuckOS install complete!"

    ;;

  find)
    handshaker_port=7887
    echo "---> Seeking ducks, please be patient..."
    subnet=`ifconfig | grep broadcast | cut -d' ' -f2 | cut -d'.' -f1-3`
    for ((host=0; host<=255; host++));
    do
      ip=$subnet.$host
      response=`curl -m1 --connect-timeout 1 $ip:$handshaker_port 2>&1`
      if [[ $response =~ "reply" ]];
      then
        echo "Quack! DuckOS detected on IP: "$ip
      fi
    done
    ;;

  help)
    cat<<EOF
    write           Writes DuckOS onto a present SD Card / USB Drive
    find            Searches for DuckOS hosts on the current network
    help            Prints the list of commands
EOF
    ;;

  *)
    # @TODO bind any other commmands as passthrough?
    #
    # $ echo 'Hello world!' > app.js
    # $ git init; git add app.js
    # $ git commit -m "First release"
    # $ git push duck@10.0.1.15 master
    # ---> Node.js app detected...
    # ===> Application deployed
    #      http://10.0.1.15
    ;;

esac

