#!/usr/bin/env bash

# curl duckos.io/install | sh
# wget duckos.io/install -O - | sh

# duck_source="https://raw.github.com/supermario/duck/master/duck"
duck_source="http://localhost/duckos/site/duck"

curl $duck_source -o /usr/local/bin/dokku
