#!/usr/bin/env bash

# curl duckos.io/install | sh
# wget duckos.io/install -O - | sh

duck_source="https://raw.githubusercontent.com/supermario/duckos/master/duck"

curl $duck_source -o /usr/local/bin/duck
